### PR TITLE
Fix timeout config overridden

### LINKED ISSUE #189: If we configure more than one clusters in conf.yaml, the timeout field of former cluster will be overridden
**What happened**:

If we configure more than one cluster in `conf.yaml`, the timeout field (connect_timeout and request_timeout) of the former cluster will be overridden.

**Solution**:

We can move the timeout config outside the clusters.

### PR DESCRIPTION
**Pull request by alchemy-lee**
**What this PR does**:

This PR moves the timeout config outside the clusters. In detail, it moves `connect_timeout` and `request_timeout` from `clusters` into `timeout_config` in ` conf.yaml`.

**Which issue(s) this PR fixes**:

Fixes #189

### CODE REVIEW

**Review by xiaoliu10 — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]

File: pkg/config/config_load_test.go [hunk 1]
```diff
@@ -134,6 +132,10 @@ func TestMain(m *testing.M) {
 					},
 				},
 			},
+			TimeoutConfig: model.TimeoutConfig{
+				ConnectTimeoutStr: "5s",
+				RequestTimeoutStr: "10s",
+			},
```
Comment (williamfeng323) [inline pkg/config/config_load_test.go:138]: can we add 1-2 tests to ensure the timeout config works?

**Review by williamfeng323 — APPROVED** [review]
