### PR TITLE
fix: traffic filter fix weight strategy and error handle within Apply method.

### LINKED ISSUE #402: GSoC 2022: Pixiu Traffic Distribution Mode Implementation
The gateway should provides the ability to distribute traffic, which makes it easier to build service o&M capabilities such as Canary testing and blue and green publishing.

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

### PR DESCRIPTION
**Pull request by maxingg**
**Which issue(s) this PR fixes**:

Fixes #402

### CODE REVIEW

File: pixiu/pkg/filter/traffic/traffic.go [hunk 1]
```diff
@@ -89,42 +94,79 @@ func (factory *FilterFactory) Config() interface{} {
...
+			if _, ok := factory.record[cluster.CanaryByHeader]; ok {
+				return errors.New("duplicate canary-by-header values")
+			} else {
+				factory.record[cluster.CanaryByHeader] = struct{}{}
+				wp.header = cluster.CanaryByHeader
+			}
+		}
+		if cluster.CanaryWeight > 0 && cluster.CanaryWeight <= 100 {
+			if up+cluster.CanaryWeight > 100 {
+				return errors.New(fmt.Sprintf("[dubbo-go-pixiu] clusters' weight sum more than 100 in %v service!", cluster.Router))
```
Comment (baerwang) [inline pixiu/pkg/filter/traffic/traffic.go]: use **fmt.Errorf**

**Comment by baerwang** [comment]
pls fix ci(lint)

**Review by mark4z — APPROVED** [review]

**Review by baerwang — APPROVED** [review]

**Review by ma642 — APPROVED** [review]

**Review by AlbumenJ — APPROVED** [review]
