### PR TITLE
remove unused types JTypeMapper check & support default types.

### LINKED ISSUE #592: [BUG] Dubbo proxy "client call err: set target fail: Types invalid com.XX.cx.XXDTO"
**What happened**:
When use custom Java Object on dubbo Java v2.7.23 Dubbo proxy error "client call err: set target fail: Types invalid com.XX.cx.XXDTO"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by mark4z**
**What this PR does**:
[remove unused types JTypeMapper check & support default types.](https://github.com/apache/dubbo-go-pixiu/commit/d258c957a5d79b8abee8aaf293bf0dfadb83a566)

**Which issue(s) this PR fixes**:

Fixes #592 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pixiu/pkg/client/dubbo/option.go [hunk 1]
```diff
@@ -186,24 +186,22 @@ type paramTypesOpt struct{}
...
-			continue
-		}
-		if _, ok = constant.JTypeMapper[trimType]; !ok {
-			return errors.Errorf("Types invalid %s", trimType)
+	// empty types for func like func()
+	types := make([]string, 0)
+	if v, ok := val.(string); ok {
+		if len(v) > 0 {
+			types = strings.Split(v, ",")
+			if !ok {
```
Comment (baerwang) [inline pixiu/pkg/client/dubbo/option.go]: 这块有点问题的吧

**Review by baerwang — APPROVED** [review]
