### PR TITLE
fix(ai-gateway): Add support for content encoding in tokenizer filter

### LINKED ISSUE #705: Enhance: llm tokenizer doesn't work when response set content-encoding
llm tokenizer doesn't work when response set content-encoding

need to decode and calc llm usage

### PR DESCRIPTION
**Pull request by Alanxtl**
fix: #705 

Add support for content encoding in stream processing and update tests

### CODE REVIEW

File: pkg/filter/llm/tokenizer/tokenizer_test.go [hunk 1]
```diff
@@ -32,55 +35,174 @@ import (
...
+
+			ctx.AddHeader(constant.HeaderKeyContentEncoding, tc.encoding)
+
+			// Call the filter's Encode method
+			filter.Encode(ctx)
+
+			// Give the goroutine a moment to process the data
+			buf := make([]byte, 1024)
+			ctx.TargetResp.(*client.StreamResponse).Stream.Read(buf)
+			time.Sleep(5 * time.Millisecond)
```
Comment (AlexStocks) [inline pkg/filter/llm/tokenizer/tokenizer_test.go:204]: 没看明白，这里哪来的goroutine？

Comment (Alanxtl) [reply pkg/filter/llm/tokenizer/tokenizer_test.go:204]: 在`pkg/filter/llm/tokenizer/tokenizer.go:97`里面 对流式响应是使用goroutine处理的

File: pkg/filter/llm/tokenizer/tokenizer.go [hunk 2]
```diff
@@ -157,6 +173,36 @@ func (f *Filter) logUsage(usage map[string]any) {
...
 }
 
+// getDecompressedReader returns an io.ReadCloser that decompresses the body based on the encoding.
+func getDecompressedReader(body io.Reader, encoding string) (io.ReadCloser, error) {
+	switch encoding {
+	case constant.HeaderValueGzip:
+		return gzip.NewReader(body)
+	case constant.HeaderValueDeflate:
+		return flate.NewReader(body), nil
+	case "":
```
Comment (baerwang) [inline pkg/filter/llm/tokenizer/tokenizer.go]: case "" 删掉然后把`return io.NopCloser(body), nil` 改成default 下面

**Review by AlexStocks — APPROVED** [review]
